parser: "@typescript-eslint/parser"
extends:
  - "plugin:@typescript-eslint/recommended"
parserOptions:
  ecmaVersion: 2018
  sourceType: module
rules:
  "@typescript-eslint/no-empty-function": off
  "@typescript-eslint/no-empty-interface": off
  "@typescript-eslint/no-explicit-any": off
  "@typescript-eslint/no-use-before-define": ["error", { "functions": false, "classes": false }]
  "@typescript-eslint/no-unused-vars":
    - warn
    - ignoreRestSiblings: true
      argsIgnorePattern: "^_"
  prefer-const: ["error", { "destructuring": "all" }]
  quotes: ["error", "single", { "avoidEscape": true }]
